name: StreamCraft
version: ${project.version}
main: me.crazycranberry.streamcraft.StreamCraft
api-version: 1.20
authors: [CrazyCranberry]
description: A plugin that allows stream viewers to interact with the minecraft world.
commands:
  screfresh:
    description: Refresh yml configurations
    permission: admin
    permission-message: You do not have permission to refresh.
  screconnect:
    description: Restart the Twitch WebSocket connection
    permission: admin
    permission-message: You do not have permission to refresh.
  CreatePoll:
    description: Used to create a poll on your channel. These should be created automatically but just in case, this command exists.
  ChannelFollow:
    description: Trigger a fake follow notification. Used for testing.
  ChannelSubscribe:
    description: Trigger a fake subscribe notification. Used for testing.
  ChannelResubscribe:
    description: Trigger a fake resubscribe notification. Used for testing.
  ChannelCheer:
    description: Trigger a fake cheer notification. Used for testing.
  SubGift:
    description: Trigger a fake Sub Gift notification. Used for testing.
  PollResult:
    description: Trigger a fake Poll Result notification. Used for testing.
permissions:
  admin:
    description: StreamCraft Admin permission
    default: op
